// Données du jeu - Mots et leurs indices organisés par taille de mots
const GAME_DATA = {
    // NIVEAU FACILE (3-4 lettres) - Vert
    easy: {
        "arc": "🏹 Arme qui lance des flèches très loin",
        "eau": "💧 Liquide transparent et vital",
        "mai": "🌸 Mois du printemps",
        "août": "☀️ Mois des vacances",
        "bob": "🏗️ Éponge qui vit dans un ananas",
        "buzz": "🚀 Astronaute de Toy Story",
        "chat": "🐱 Animal de compagnie ronronnant",
        "ours": "🐻 Gros animal poilu",
        "lion": "🦁 Roi de la jungle",
        "pain": "🥖 Aliment de base fait avec de la farine",
        "rage": "😡 Sentiment de colère",
        "peur": "😰 Sentiment d'angoisse",
        "joie": "😊 Sentiment de bonheur",
        "vert": "🌿 Couleur de l'herbe et des feuilles",
        "paix": "☮️ Absence de guerre et de conflit",
        "reve": "💭 Pensée qui vient quand on dort",
        "lune": "🌙 Astre qui brille la nuit dans le ciel",
        "epee": "⚔️ Arme brillante et pointue des chevaliers",
        "fee": "🧚 Petite créature magique avec des ailes",
        "un": "1",
        "deux": "2",
        "onze": "11",
        "vélo": "🚲 Véhicule à 2 roues",
        "cinq": "5",
        "six": "6",
        "sept": "7",
        "huit": "8",
        "neuf": "9",
        "dix": "10"
    },
    
    // NIVEAU MOYEN (5-6 lettres) - Orange
    medium: {
        "ninja": "🥷 Guerrier masqué qui se déplace en silence",
        "trois": "3",
        "quatre": "4",
        "dragon": "🐉 Créature magique qui vole et crache du feu",
        "prince": "🤴 Fils du roi, héros des contes de fées",
        "reine": "👸 Femme puissante qui dirige un royaume",
        "heros": "🦸 Personne courageuse qui sauve les autres",
        "pirate": "🏴‍☠️ Aventurier des mers avec un bandeau sur l'œil",
        "batman": "🦇 Super-héros noir de Gotham",
        "tarzan": "🦍 Homme de la jungle",
        "simba": "🦁 Lion roi de Disney",
        "woody": "🤠 Cowboy de Toy Story",
        "lapin": "🐰 Animal aux longues oreilles",
        "cochon": "🐷 Animal rose qui grogne",
        "mouton": "🐑 Animal avec de la laine",
        "canard": "🦆 Oiseau aquatique",
        "poule": "🐔 Oiseau de basse-cour",
        "souris": "🐭 Petit rongeur gris",
        "burger": "🍔 Sandwich rond avec de la viande",
        "frites": "🍟 Pommes de terre frites",
        "glace": "🍦 Dessert froid et sucré",
        "bonbon": "🍭 Sucrerie colorée",
        "orange": "🍊 Fruit orange et rond",
        "voyage": "✈️ Long voyage vers un endroit",
        "volcan": "🌋 Montagne qui crache du feu",
        "espace": "🚀 Zone vide entre les planètes et étoiles",
        "foret": "🌲 Grande étendue d'arbres",
        "avion": "✈️ Véhicule qui vole",
        "bateau": "⛵ Véhicule qui flotte sur l'eau",
        "train": "🚂 Véhicule sur des rails",
        "douze": "12",
        "treize": "13",
        "quinze": "15",
        "seize": "16",
        "vingt": "20",
        "amour": "❤️ Sentiment très fort qu'on a pour quelqu'un",
        "nuage": "☁️ Vapeur d'eau dans le ciel",
        "terre": "🌍 Planète où nous vivons",
        "plage": "🏖️ Bord de mer avec du sable",
        "ocean": "🌊 Grande étendue d'eau salée",
        "panda": "🐼 Ours noir et blanc qui mange du bambou",
        "tigre": "🐅 Gros chat sauvage rayé",
        "aigle": "🦅 Oiseau de proie très grand",
        "zebre": "🦓 Cheval sauvage avec des rayures",
        "chien": "🐶 Meilleur ami de l'homme",
        "pizza": "🍕 Plat italien rond avec du fromage et de la tomate",
        "robot": "🤖 Machine intelligente qui peut bouger et parler",
        "magie": "✨ Art mystérieux qui fait apparaître des choses",
        "super": "🦸 Mot qui rend tout plus fort et plus cool",
        "livre": "📚 Objet avec des pages à lire",
        "école": "🏫 Lieu où on apprend",
        "lundi": "📅 Premier jour de la semaine",
        "mardi": "📅 Deuxième jour de la semaine",
        "jeudi": "📅 Quatrième jour de la semaine",
        "etoile": "⭐ Petite lumière qui scintille dans le ciel",
        "tortue": "🐢 Animal avec une carapace dure",
        "amitié": "🤝 Relation d'amour entre amis",
        "tresor": "💰💎 Richesse cachée que tout le monde cherche",
        "dix-sept": "17",
        "dix-huit": "18",
        "dix-neuf": "19",
        "mickey": "🐭 Souris célèbre de Disney",
        "requin": "🦈 Poisson dangereux des mers",
        "renard": "🦊 Animal rusé et orange",
        "maison": "🏠 Endroit où on habite",
        "banane": "🍌 Fruit jaune et courbé",
        "gâteau": "🎂 Dessert sucré",
        "samedi": "📅 Sixième jour de la semaine",
        "mars": "🌸 Troisième mois de l'année",
        "avril": "🌸 Quatrième mois de l'année",
        "juin": "☀️ Sixième mois de l'année",
        "espoir": "🌟 Sentiment d'espoir pour l'avenir",
        "girafe": "🦒 Animal très grand avec un long cou"
    },
    
    // NIVEAU DIFFICILE (7+ lettres) - Rouge
    hard: {
        "baleine": "🐋 Très gros animal marin",
        "chameau": "🐪 Animal du désert avec des bosses",
        "famille": "👨‍👩‍👧‍👦 Groupe de personnes liées",
        "abeille": "🐝 Insecte qui fait du miel",
        "bonheur": "😊 Sentiment de grande joie",
        "février": "❄️ Deuxième mois de l'année",
        "décembre": "❄️ Douzième mois de l'année",
        "tempête": "⛈️ Mauvais temps avec vent et pluie",
        "rivière": "🌊 Cours d'eau",
        "lumiere": "💡 Ce qui éclaire et rend visible",
        "mercredi": "📅 Troisième jour de la semaine",
        "vendredi": "📅 Cinquième jour de la semaine",
        "dimanche": "📅 Jour de repos",
        "janvier": "❄️ Premier mois de l'année",
        "juillet": "☀️ Septième mois de l'année",
        "septembre": "🍂 Neuvième mois de l'année",
        "octobre": "🍂 Dixième mois de l'année",
        "novembre": "🍂 Onzième mois de l'année",
        "courage": "💪 Force face à la peur",
        "sourire": "😊 Expression du visage qui montre la joie",
        "heureux": "😄 Sentiment de grande joie et de bonheur",
        "mystere": "🔍 Enigme mystérieuse à résoudre",
        "magique": "🎩 Pouvoir surnaturel qui fait des miracles",
        "aventure": "🗺️ Voyage excitant plein de découvertes",
        "montagne": "⛰️ Grande élévation de terre",
        "quatorze": "14",
        "carotte": "🥕 Légume orange",
        "sorcier": "🧙 Homme sage qui connaît tous les sorts",
        "cristal": "💎 Pierre précieuse et brillante",
        "liberté": "🕊️ Droit de faire ce qu'on veut",
        "chocolat": "🍫 Friandise brune et sucrée",
        "chateau": "🏰 Grande maison fortifiée des rois",
        "courageux": "💪 Qualité de quelqu'un qui n'a pas peur",
        "magicien": "🧙 Personne qui pratique la magie",
        "princesse": "👸 Fille du roi et de la reine",
        "monstre": "👹 Créature effrayante et dangereuse",
        "tonnerre": "⚡ Bruit fort pendant l'orage",
        "arcenciel": "🌈 Arc-en-ciel avec toutes les couleurs",
        "papillon": "🦋 Insecte coloré qui vole",
        "elephant": "🐘 Très gros animal avec une trompe",
        "dauphin": "🐬 Animal marin intelligent et joueur",
        "pingouin": "🐧 Oiseau qui ne vole pas, nage bien",
        "spiderman": "🕷️ Super-héros qui grimpe aux murs",
        "superman": "🦸 Super-héros qui vole",
        "aladdin": "🧞 Jeune homme avec une lampe magique",
        "téléphone": "📱 Appareil pour appeler",
        "ordinateur": "💻 Machine pour travailler",
        "voiture": "🚗 Véhicule à 4 roues",
        "hôpital": "🏥 Lieu où on soigne",
        "fromage": "🧀 Produit laitier",
        "couronne": "👑 Bijou doré que portent les rois et reines",
        "chevalier": "⚔️ Guerrier courageux qui protège les gens"
    }
};

// Export pour utilisation dans d'autres fichiers
if (typeof module !== 'undefined' && module.exports) {
    module.exports = GAME_DATA;
}