// Données du jeu - Mots et leurs indices organisés par difficulté
const GAME_DATA = {
    // NIVEAU FACILE (4 lettres) - Vert
    easy: {
        "pizza": "🍕 Plat italien rond avec du fromage et de la tomate",
        "robot": "🤖 Machine intelligente qui peut bouger et parler",
        "dragon": "🐉 Créature magique qui vole et crache du feu",
        "ninja": "🥷 Guerrier masqué qui se déplace en silence",
        "magie": "✨ Art mystérieux qui fait apparaître des choses",
        "super": "🦸 Mot qui rend tout plus fort et plus cool",
        "lune": "🌙 Astre qui brille la nuit dans le ciel",
        "etoile": "⭐ Petite lumière qui scintille dans le ciel",
        "arc": "🏹 Arme qui lance des flèches très loin",
        "couronne": "👑 Bijou doré que portent les rois et reines",
        "epee": "⚔️ Arme brillante et pointue des chevaliers",
        "chateau": "🏰 Grande maison fortifiée des rois",
        "prince": "🤴 Fils du roi, héros des contes de fées",
        "fee": "🧚 Petite créature magique avec des ailes",
        "sorcier": "🧙 Homme sage qui connaît tous les sorts",
        "chevalier": "⚔️ Guerrier courageux qui protège les gens",
        "reine": "👸 Femme puissante qui dirige un royaume",
        "tresor": "💰💎 Richesse cachée que tout le monde cherche",
        "aventure": "🗺️ Voyage excitant plein de découvertes",
        "mystere": "🔍 Enigme mystérieuse à résoudre",
        "magique": "🎩 Pouvoir surnaturel qui fait des miracles",
        "heros": "🦸 Personne courageuse qui sauve les autres",
        "reve": "💭 Pensée qui vient quand on dort",
        "sourire": "😊 Expression du visage qui montre la joie",
        "heureux": "😄 Sentiment de grande joie et de bonheur",
        "paix": "☮️ État où il n'y a pas de guerre ni de violence",
        "amour": "❤️ Sentiment très fort qu'on a pour quelqu'un",
        "espoir": "🌟 Sentiment d'espoir pour l'avenir",
        "courageux": "💪 Qualité de quelqu'un qui n'a pas peur",
        "panda": "🐼 Ours noir et blanc qui mange du bambou",
        "espace": "🚀 Zone vide entre les planètes et étoiles",
        "ocean": "🌊 Grande étendue d'eau salée",
        "plage": "🏖️ Bord de mer avec du sable",
        "nuage": "☁️ Vapeur d'eau dans le ciel",
        "lumiere": "💡 Ce qui éclaire et rend visible",
        "paix": "☮️ Absence de guerre et de conflit",
        "vert": "🌿 Couleur de l'herbe et des feuilles",
        "eau": "💧 Liquide transparent et vital",
        "terre": "🌍 Planète où nous vivons"
    },
    
    // NIVEAU MOYEN (5 lettres) - Orange
    medium: {
        "pirate": "🏴‍☠️ Aventurier des mers avec un bandeau sur l'œil",
        "chateau": "🏰 Grande maison fortifiée des rois",
        "prince": "🤴 Fils du roi, héros des contes de fées",
        "sorcier": "🧙 Homme sage qui connaît tous les sorts",
        "chevalier": "⚔️ Guerrier courageux qui protège les gens",
        "reine": "👸 Femme puissante qui dirige un royaume",
        "tresor": "💰💎 Richesse cachée que tout le monde cherche",
        "aventure": "🗺️ Voyage excitant plein de découvertes",
        "mystere": "🔍 Enigme mystérieuse à résoudre",
        "magique": "🎩 Pouvoir surnaturel qui fait des miracles",
        "heros": "🦸 Personne courageuse qui sauve les autres",
        "reve": "💭 Pensée qui vient quand on dort",
        "sourire": "😊 Expression du visage qui montre la joie",
        "heureux": "😄 Sentiment de grande joie et de bonheur",
        "paix": "☮️ État où il n'y a pas de guerre ni de violence",
        "amour": "❤️ Sentiment très fort qu'on a pour quelqu'un",
        "espoir": "🌟 Sentiment d'espoir pour l'avenir",
        "courageux": "💪 Qualité de quelqu'un qui n'a pas peur",
        "foret": "🌲 Grande étendue d'arbres",
        "magicien": "🧙 Personne qui pratique la magie",
        "chevalier": "⚔️ Guerrier noble à cheval",
        "princesse": "👸 Fille du roi et de la reine",
        "monstre": "👹 Créature effrayante et dangereuse",
        "tresor": "💰 Richesse cachée et précieuse",
        "aventure": "🗺️ Voyage excitant et dangereux",
        "mystere": "🔍 Chose secrète et inconnue",
        "voyage": "✈️ Long voyage vers un endroit",
        "cristal": "💎 Pierre précieuse et brillante",
        "tonnerre": "⚡ Bruit fort pendant l'orage",
        "arcenciel": "🌈 Arc-en-ciel avec toutes les couleurs",
        "papillon": "🦋 Insecte coloré qui vole",
        "elephant": "🐘 Très gros animal avec une trompe",
        "girafe": "🦒 Animal très grand avec un long cou",
        "dauphin": "🐬 Animal marin intelligent et joueur",
        "tigre": "🐅 Gros chat sauvage rayé",
        "aigle": "🦅 Oiseau de proie très grand",
        "requin": "🦈 Poisson dangereux des mers",
        "baleine": "🐋 Très gros animal marin",
        "chameau": "🐪 Animal du désert avec des bosses",
        "zebre": "🦓 Cheval sauvage avec des rayures",
        "pingouin": "🐧 Oiseau qui ne vole pas, nage bien",
        "tortue": "🐢 Animal avec une carapace dure"
    },
    
    // NIVEAU DIFFICILE (6+ lettres) - Rouge
    hard: {
        "chateau": "🏰 Grande construction fortifiée des rois",
        "foret": "🌲 Grande étendue d'arbres",
        "magicien": "🧙 Personne qui pratique la magie",
        "pirate": "🏴‍☠️ Personne qui attaque les navires",
        "dragon": "🐉 Créature mythique qui crache du feu",
        "chevalier": "⚔️ Guerrier noble à cheval",
        "princesse": "👸 Fille du roi et de la reine",
        "monstre": "👹 Créature effrayante et dangereuse",
        "tresor": "💰 Richesse cachée et précieuse",
        "aventure": "🗺️ Voyage excitant et dangereux",
        "mystere": "🔍 Chose secrète et inconnue",
        "voyage": "✈️ Long voyage vers un endroit",
        "cristal": "💎 Pierre précieuse et brillante",
        "tonnerre": "⚡ Bruit fort pendant l'orage",
        "arcenciel": "🌈 Arc-en-ciel avec toutes les couleurs",
        "papillon": "🦋 Insecte coloré qui vole",
        "elephant": "🐘 Très gros animal avec une trompe",
        "girafe": "🦒 Animal très grand avec un long cou",
        "dauphin": "🐬 Animal marin intelligent et joueur",
        "courageux": "💪 Qualité de quelqu'un qui n'a pas peur",
        "mystere": "🔍 Enigme mystérieuse à résoudre",
        "magique": "🎩 Pouvoir surnaturel qui fait des miracles",
        "aventure": "🗺️ Voyage excitant plein de découvertes",
        "tresor": "💰💎 Richesse cachée que tout le monde cherche",
        "sorcier": "🧙 Homme sage qui connaît tous les sorts",
        "chevalier": "⚔️ Guerrier courageux qui protège les gens",
        "princesse": "👸 Fille du roi et de la reine",
        "monstre": "👹 Créature effrayante et dangereuse",
        "cristal": "💎 Pierre précieuse et brillante",
        "tonnerre": "⚡ Bruit fort pendant l'orage",
        "arcenciel": "🌈 Arc-en-ciel avec toutes les couleurs",
        "papillon": "🦋 Insecte coloré qui vole",
        "elephant": "🐘 Très gros animal avec une trompe",
        "girafe": "🦒 Animal très grand avec un long cou",
        "dauphin": "🐬 Animal marin intelligent et joueur",
        "aventure": "🗺️ Voyage excitant plein de découvertes",
        "mystere": "🔍 Enigme mystérieuse à résoudre",
        "magique": "🎩 Pouvoir surnaturel qui fait des miracles",
        "courageux": "💪 Qualité de quelqu'un qui n'a pas peur",
        "princesse": "👸 Fille du roi et de la reine",
        "monstre": "👹 Créature effrayante et dangereuse",
        "cristal": "💎 Pierre précieuse et brillante",
        "tonnerre": "⚡ Bruit fort pendant l'orage",
        "arcenciel": "🌈 Arc-en-ciel avec toutes les couleurs",
        "papillon": "🦋 Insecte coloré qui vole",
        "elephant": "🐘 Très gros animal avec une trompe",
        "girafe": "🦒 Animal très grand avec un long cou",
        "dauphin": "🐬 Animal marin intelligent et joueur"
    }
};

// Export pour utilisation dans d'autres fichiers
if (typeof module !== 'undefined' && module.exports) {
    module.exports = GAME_DATA;
}