// NIVEAU MOYEN (5-6 lettres) - Mots de difficulté moyenne
// "[a-zàâäéèêëïîôùûüÿœæç-]{5,6}":
const DATA_MEDIUM = {
    "ninja": "🥷 Guerrier masqué qui se déplace en silence",
    "trois": "3",
    "quatre": "4",
    "dragon": "🐉 Créature magique qui vole et crache du feu",
    "prince": "🤴 Fils du roi, héros des contes de fées",
    "reine": "👸 Femme puissante qui dirige un royaume",
    "heros": "🦸 Personne courageuse qui sauve les autres",
    "pirate": "🏴‍☠️ Aventurier des mers avec un bandeau sur l'œil",
    "batman": "🦇 Super-héros noir de Gotham",
    "tarzan": "🦍 Homme de la jungle",
    "simba": "🦁 Lion roi de Disney",
    "woody": "🤠 Cowboy de Toy Story",
    "lapin": "🐰 Animal aux longues oreilles",
    "cochon": "🐷 Animal rose qui grogne",
    "mouton": "🐑 Animal avec de la laine",
    "canard": "🦆 Oiseau aquatique",
    "poule": "🐔 Oiseau de basse-cour",
    "souris": "🐭 Petit rongeur gris",
    "burger": "🍔 Sandwich rond avec de la viande",
    "frites": "🍟 Pommes de terre frites",
    "glace": "🍦 Dessert froid et sucré",
    "bonbon": "🍭 Sucrerie colorée",
    "orange": "🍊 Fruit orange et rond",
    "voyage": "✈️ Long voyage vers un endroit",
    "volcan": "🌋 Montagne qui crache du feu",
    "espace": "🚀 Zone vide entre les planètes et étoiles",
    "foret": "🌲 Grande étendue d'arbres",
    "avion": "✈️ Véhicule qui vole",
    "bateau": "⛵ Véhicule qui flotte sur l'eau",
    "train": "🚂 Véhicule sur des rails",
    "douze": "12",
    "treize": "13",
    "quinze": "15",
    "seize": "16",
    "vingt": "20",
    "amour": "❤️ Sentiment très fort qu'on a pour quelqu'un",
    "nuage": "☁️ Vapeur d'eau dans le ciel",
    "terre": "🌍 Planète où nous vivons",
    "plage": "🏖️ Bord de mer avec du sable",
    "ocean": "🌊 Grande étendue d'eau salée",
    "panda": "🐼 Ours noir et blanc qui mange du bambou",
    "tigre": "🐅 Gros chat sauvage rayé",
    "aigle": "🦅 Oiseau de proie très grand",
    "zebre": "🦓 Cheval sauvage avec des rayures",
    "chien": "🐶 Meilleur ami de l'homme",
    "pizza": "🍕 Plat italien rond avec du fromage et de la tomate",
    "robot": "🤖 Machine intelligente qui peut bouger et parler",
    "magie": "✨ Art mystérieux qui fait apparaître des choses",
    "super": "🦸 Mot qui rend tout plus fort et plus cool",
    "livre": "📚 Objet avec des pages à lire",
    "école": "🏫 Lieu où on apprend",
    "lundi": "📅 Premier jour de la semaine",
    "mardi": "📅 Deuxième jour de la semaine",
    "jeudi": "📅 Quatrième jour de la semaine",
    "etoile": "⭐ Petite lumière qui scintille dans le ciel",
    "tortue": "🐢 Animal avec une carapace dure",
    "amitié": "🤝 Relation d'amour entre amis",
    "tresor": "💰💎 Richesse cachée que tout le monde cherche",
    "mickey": "🐭 Souris célèbre de Disney",
    "requin": "🦈 Poisson dangereux des mers",
    "renard": "🦊 Animal rusé et orange",
    "maison": "🏠 Endroit où on habite",
    "banane": "🍌 Fruit jaune et courbé",
    "gâteau": "🎂 Dessert sucré",
    "samedi": "📅 Sixième jour de la semaine",
    "avril": "🌸 Quatrième mois de l'année",
    "espoir": "🌟 Sentiment d'espoir pour l'avenir",
    "girafe": "🦒 Animal très grand avec un long cou",
    "soleil": "☀️ Étoile qui brille le jour",
    "étoile": "⭐ Lumière dans le ciel la nuit",
    "jardin": "🌻 Espace avec des fleurs et plantes",
    "fleur": "🌸 Plante colorée et parfumée",
    "arbre": "🌳 Grande plante avec un tronc",
    "herbe": "🌿 Plante verte au sol",
    "pluie": "🌧️ Eau qui tombe du ciel",
    "neige": "❄️ Flocons blancs en hiver",
    "nuages": "☁️ Masses blanches dans le ciel",
    "saison": "🍂 Période de l'année",
    "hiver": "❄️ Saison froide",
    "sport": "⚽ Activité physique",
    "ballon": "⚽ Objet rond pour jouer",
    "match": "🏆 Compétition sportive",
    "tennis": "🎾 Sport avec raquette",
    "rugby": "🏉 Sport avec ballon ovale",
    "course": "🏃 Courir vite",
    "muscle": "💪 Partie du corps qui donne la force",
    "santé": "❤️ État de bien-être",
    "corps": "🧍 Ensemble du physique",
    "visage": "😊 Partie avant de la tête",
    "barbe": "🧔 Poils sur le visage",
    "dents": "🦷 Pour mâcher la nourriture",
    "langue": "👅 Pour goûter",
    "jambe": "🦵 Pour marcher et courir",
    "doigt": "👆 Partie de la main",
    "ongle": "💅 Bout dur du doigt",
    "genou": "🦵 Articulation de la jambe",
    "coude": "💪 Articulation du bras",
    "épaule": "🤷 Haut du bras",
    "ventre": "🤰 Partie du corps avec l'estomac",
    "coeur": "❤️ Organe qui bat dans la poitrine",
    "poumon": "🫁 Pour respirer",
    "table": "🪑 Meuble pour manger",
    "chaise": "🪑 Meuble pour s'asseoir",
    "bureau": "🖥️ Meuble pour travailler",
    "lampe": "💡 Pour éclairer",
    "miroir": "🪞 Pour se regarder",
    "rideau": "🪟 Cache la fenêtre",
    "tapis": "🧶 Sur le sol",
    "radio": "📻 Pour écouter de la musique",
    "chant": "🎤 Musique avec la voix",
    "danse": "💃 Bouger en rythme",
    "photo": "📷 Image capturée",
    "dessin": "🎨 Image faite à la main",
    "rouge": "🔴 Couleur du sang",
    "jaune": "🟡 Couleur du soleil",
    "blanc": "⚪ Couleur de la neige",
    "violet": "🟣 Couleur entre rouge et bleu",
    "marron": "🟤 Couleur du bois",
    "pomme": "🍎 Fruit rouge ou vert",
    "poire": "🍐 Fruit vert en forme de goutte",
    "raisin": "🍇 Petits fruits en grappe",
    "cerise": "🍒 Petit fruit rouge",
    "fraise": "🍓 Fruit rouge avec des graines",
    "citron": "🍋 Fruit jaune et acide",
    "melon": "🍈 Gros fruit vert ou orange",
    "tomate": "🍅 Fruit rouge pour la sauce",
    "salade": "🥗 Légumes verts",
    "radis": "🌶️ Petit légume rose",
    "poivre": "🌶️ Épice qui pique",
    "sucre": "🍬 Rend les choses sucrées",
    "farine": "🌾 Poudre pour faire du pain",
    "huile": "🫒 Liquide pour cuisiner",
    "beurre": "🧈 Produit laitier à tartiner",
    "yaourt": "🥛 Produit laitier onctueux",
    "viande": "🥩 Chair d'animal",
    "poulet": "🍗 Viande de poule",
    "jambon": "🥓 Viande de porc",
    "soupe": "🍲 Plat liquide chaud",
    "repas": "🍽️ Moment où on mange",
    "petit": "📏 Pas grand",
    "grand": "📏 Très haut",
    "mince": "📏 Pas épais",
    "court": "📏 Petite distance",
    "rapide": "⚡ Très vite",
    "faible": "😔 Pas fort",
    "chaud": "🔥 Haute température",
    "froid": "🧊 Basse température"
};

