// NIVEAU MOYEN (5-6 lettres) - Mots de difficulté moyenne
// Format: { hint: "indice", cat: ID }
// IDs: 1=Animaux, 2=Nourriture, 3=Nature, 4=Véhicules, 5=Nombres, 6=Temps,
//      7=Émotions, 8=Personnages, 9=Corps, 10=Maison, 11=Couleurs, 12=Objets, 13=Sports, 99=Divers

const DATA_MEDIUM = {
    // Animaux (1)
    "lapin": { hint: "🐰 Animal aux longues oreilles", cat: 1 },
    "cochon": { hint: "🐷 Animal rose qui grogne", cat: 1 },
    "mouton": { hint: "🐑 Animal avec de la laine", cat: 1 },
    "canard": { hint: "🦆 Oiseau aquatique", cat: 1 },
    "poule": { hint: "🐔 Oiseau de basse-cour", cat: 1 },
    "souris": { hint: "🐭 Petit rongeur gris", cat: 1 },
    "panda": { hint: "🐼 Ours noir et blanc qui mange du bambou", cat: 1 },
    "tigre": { hint: "🐅 Gros chat sauvage rayé", cat: 1 },
    "aigle": { hint: "🦅 Oiseau de proie très grand", cat: 1 },
    "zèbre": { hint: "🦓 Cheval sauvage avec des rayures", cat: 1 },
    "chien": { hint: "🐶 Meilleur ami de l'homme", cat: 1 },
    "tortue": { hint: "🐢 Animal avec une carapace dure", cat: 1 },
    "requin": { hint: "🦈 Poisson dangereux des mers", cat: 1 },
    "renard": { hint: "🦊 Animal rusé et orange", cat: 1 },
    "girafe": { hint: "🦒 Animal très grand avec un long cou", cat: 1 },
    
    // Nourriture (2)
    "burger": { hint: "🍔 Sandwich rond avec de la viande", cat: 2 },
    "frites": { hint: "🍟 Pommes de terre frites", cat: 2 },
    "glace": { hint: "🍦 Dessert froid et sucré", cat: 2 },
    "bonbon": { hint: "🍭 Sucrerie colorée", cat: 2 },
    "orange": { hint: "🍊 Fruit orange et rond", cat: 2 },
    "pizza": { hint: "🍕 Plat italien rond avec du fromage et de la tomate", cat: 2 },
    "banane": { hint: "🍌 Fruit jaune et courbé", cat: 2 },
    "gâteau": { hint: "🎂 Dessert sucré", cat: 2 },
    "pomme": { hint: "🍎 Fruit rouge ou vert", cat: 2 },
    "poire": { hint: "🍐 Fruit vert en forme de goutte", cat: 2 },
    "raisin": { hint: "🍇 Petits fruits en grappe", cat: 2 },
    "cerise": { hint: "🍒 Petit fruit rouge", cat: 2 },
    "fraise": { hint: "🍓 Fruit rouge avec des graines", cat: 2 },
    "citron": { hint: "🍋 Fruit jaune et acide", cat: 2 },
    "melon": { hint: "🍈 Gros fruit vert ou orange", cat: 2 },
    "tomate": { hint: "🍅 Fruit rouge pour la sauce", cat: 2 },
    "salade": { hint: "🥗 Légumes verts", cat: 2 },
    "radis": { hint: "🌶️ Petit légume rose", cat: 2 },
    "poivre": { hint: "🌶️ Épice qui pique", cat: 2 },
    "sucre": { hint: "🍬 Rend les choses sucrées", cat: 2 },
    "farine": { hint: "🌾 Poudre pour faire du pain", cat: 2 },
    "huile": { hint: "🫒 Liquide pour cuisiner", cat: 2 },
    "beurre": { hint: "🧈 Produit laitier à tartiner", cat: 2 },
    "yaourt": { hint: "🥛 Produit laitier onctueux", cat: 2 },
    "viande": { hint: "🥩 Chair d'animal", cat: 2 },
    "poulet": { hint: "🍗 Viande de poule", cat: 2 },
    "jambon": { hint: "🥓 Viande de porc", cat: 2 },
    "soupe": { hint: "🍲 Plat liquide chaud", cat: 2 },
    "repas": { hint: "🍽️ Moment où on mange", cat: 2 },
    
    // Nature (3)
    "volcan": { hint: "🌋 Montagne qui crache du feu", cat: 3 },
    "espace": { hint: "🚀 Zone vide entre les planètes et étoiles", cat: 3 },
    "forêt": { hint: "🌲 Grande étendue d'arbres", cat: 3 },
    "nuage": { hint: "☁️ Vapeur d'eau dans le ciel", cat: 3 },
    "terre": { hint: "🌍 Planète où nous vivons", cat: 3 },
    "plage": { hint: "🏖️ Bord de mer avec du sable", cat: 3 },
    "océan": { hint: "🌊 Grande étendue d'eau salée", cat: 3 },
    "soleil": { hint: "☀️ Étoile qui brille le jour", cat: 3 },
    "étoile": { hint: "⭐ Lumière dans le ciel la nuit", cat: 3 },
    "jardin": { hint: "🌻 Espace avec des fleurs et plantes", cat: 3 },
    "fleur": { hint: "🌸 Plante colorée et parfumée", cat: 3 },
    "arbre": { hint: "🌳 Grande plante avec un tronc", cat: 3 },
    "herbe": { hint: "🌿 Plante verte au sol", cat: 3 },
    "pluie": { hint: "🌧️ Eau qui tombe du ciel", cat: 3 },
    "neige": { hint: "❄️ Flocons blancs en hiver", cat: 3 },
    "nuages": { hint: "☁️ Masses blanches dans le ciel", cat: 3 },
    "saison": { hint: "🍂 Période de l'année", cat: 3 },
    "hiver": { hint: "❄️ Saison froide", cat: 3 },
    "été": { hint: "☀️ Saison chaude", cat: 3 },
    
    // Véhicules (4)
    "avion": { hint: "✈️ Véhicule qui vole", cat: 4 },
    "bateau": { hint: "⛵ Véhicule qui flotte sur l'eau", cat: 4 },
    "train": { hint: "🚂 Véhicule sur des rails", cat: 4 },
    
    // Nombres (5)
    "trois": { hint: "3️⃣ ", cat: 5 },
    "quatre": { hint: "4️⃣ ", cat: 5 },
    "douze": { hint: "🔢 (12)", cat: 5 },
    "treize": { hint: "🔢 (13)", cat: 5 },
    "quinze": { hint: "🔢 (15)", cat: 5 },
    "seize": { hint: "🔢 (16)", cat: 5 },
    "vingt": { hint: "🔢 (20)", cat: 5 },
    "dix-sept": { hint: "🔢 (17)", cat: 5 },
    "dix-huit": { hint: "🔢 (18)", cat: 5 },
    "dix-neuf": { hint: "🔢 (19)", cat: 5 },
    
    // Temps (6)
    "lundi": { hint: "📅 Premier jour de la semaine", cat: 6 },
    "mardi": { hint: "📅 Deuxième jour de la semaine", cat: 6 },
    "jeudi": { hint: "📅 Quatrième jour de la semaine", cat: 6 },
    "samedi": { hint: "📅 Sixième jour de la semaine", cat: 6 },
    "avril": { hint: "🌸 Quatrième mois de l'année", cat: 6 },
    
    // Émotions (7)
    "amour": { hint: "❤️ Sentiment très fort qu'on a pour quelqu'un", cat: 7 },
    "espoir": { hint: "🌟 Sentiment d'espoir pour l'avenir", cat: 7 },
    "amitié": { hint: "🤝 Relation d'amour entre amis", cat: 7 },
    
    // Personnages (8)
    "ninja": { hint: "🥷 Guerrier masqué qui se déplace en silence", cat: 8 },
    "dragon": { hint: "🐉 Créature magique qui vole et crache du feu", cat: 8 },
    "prince": { hint: "🤴 Fils du roi, héros des contes de fées", cat: 8 },
    "reine": { hint: "👸 Femme puissante qui dirige un royaume", cat: 8 },
    "héros": { hint: "🦸 Personne courageuse qui sauve les autres", cat: 8 },
    "pirate": { hint: "🏴‍☠️ Aventurier des mers avec un bandeau sur l'œil", cat: 8 },
    "batman": { hint: "🦇 Super-héros noir de Gotham", cat: 8 },
    "tarzan": { hint: "🦍 Homme de la jungle", cat: 8 },
    "simba": { hint: "🦁 Lion roi de Disney", cat: 8 },
    "woody": { hint: "🤠 Cowboy de Toy Story", cat: 8 },
    "mickey": { hint: "🐭 Souris célèbre de Disney", cat: 8 },
    
    // Corps (9)
    "muscle": { hint: "💪 Partie du corps qui donne la force", cat: 9 },
    "santé": { hint: "❤️ État de bien-être", cat: 9 },
    "corps": { hint: "🧍 Ensemble du physique", cat: 9 },
    "visage": { hint: "😊 Partie avant de la tête", cat: 9 },
    "cheveux": { hint: "💇 Poils sur la tête", cat: 9 },
    "barbe": { hint: "🧔 Poils sur le visage", cat: 9 },
    "dents": { hint: "🦷 Pour mâcher la nourriture", cat: 9 },
    "langue": { hint: "👅 Pour goûter", cat: 9 },
    "jambe": { hint: "🦵 Pour marcher et courir", cat: 9 },
    "doigt": { hint: "👆 Partie de la main", cat: 9 },
    "ongle": { hint: "💅 Bout dur du doigt", cat: 9 },
    "genou": { hint: "🦵 Articulation de la jambe", cat: 9 },
    "coude": { hint: "💪 Articulation du bras", cat: 9 },
    "épaule": { hint: "🤷 Haut du bras", cat: 9 },
    "ventre": { hint: "🤰 Partie du corps avec l'estomac", cat: 9 },
    "cœur": { hint: "❤️ Organe qui bat dans la poitrine", cat: 9 },
    "poumon": { hint: "🫁 Pour respirer", cat: 9 },
    "cerveau": { hint: "🧠 Organe pour penser", cat: 9 },
    
    // Maison (10)
    "maison": { hint: "🏠 Endroit où on habite", cat: 10 },
    "table": { hint: "🪑 Meuble pour manger", cat: 10 },
    "chaise": { hint: "🪑 Meuble pour s'asseoir", cat: 10 },
    "bureau": { hint: "🖥️ Meuble pour travailler", cat: 10 },
    "lampe": { hint: "💡 Pour éclairer", cat: 10 },
    "miroir": { hint: "🪞 Pour se regarder", cat: 10 },
    "rideau": { hint: "🪟 Cache la fenêtre", cat: 10 },
    "tapis": { hint: "🧶 Sur le sol", cat: 10 },
    "coussin": { hint: "🛋️ Objet moelleux pour s'asseoir", cat: 10 },
    "armoire": { hint: "🚪 Meuble pour ranger les vêtements", cat: 10 },
    "étagère": { hint: "📚 Meuble pour ranger les livres", cat: 10 },
    
    // Couleurs (11)
    "couleur": { hint: "🎨 Teinte, nuance", cat: 11 },
    "rouge": { hint: "🔴 Couleur du sang", cat: 11 },
    "jaune": { hint: "🟡 Couleur du soleil", cat: 11 },
    "blanc": { hint: "⚪ Couleur de la neige", cat: 11 },
    "violet": { hint: "🟣 Couleur entre rouge et bleu", cat: 11 },
    "marron": { hint: "🟤 Couleur du bois", cat: 11 },
    
    // Objets (12)
    "livre": { hint: "📚 Objet avec des pages à lire", cat: 12 },
    "étoile": { hint: "⭐ Petite lumière qui scintille dans le ciel", cat: 12 },
    "trésor": { hint: "💰💎 Richesse cachée que tout le monde cherche", cat: 12 },
    
    // Sports (13)
    "sport": { hint: "⚽ Activité physique", cat: 13 },
    "ballon": { hint: "⚽ Objet rond pour jouer", cat: 13 },
    "match": { hint: "🏆 Compétition sportive", cat: 13 },
    "tennis": { hint: "🎾 Sport avec raquette", cat: 13 },
    "rugby": { hint: "🏉 Sport avec ballon ovale", cat: 13 },
    "course": { hint: "🏃 Courir vite", cat: 13 },
    "natation": { hint: "🏊 Sport dans l'eau", cat: 13 },
    
    // Divers (99)
    "voyage": { hint: "✈️ Long voyage vers un endroit", cat: 99 },
    "robot": { hint: "🤖 Machine intelligente qui peut bouger et parler", cat: 99 },
    "magie": { hint: "✨ Art mystérieux qui fait apparaître des choses", cat: 99 },
    "super": { hint: "🦸 Mot qui rend tout plus fort et plus cool", cat: 99 },
    "école": { hint: "🏫 Lieu où on apprend", cat: 99 },
    "radio": { hint: "📻 Pour écouter de la musique", cat: 99 },
    "musique": { hint: "🎵 Sons agréables et harmonieux", cat: 99 },
    "chant": { hint: "🎤 Musique avec la voix", cat: 99 },
    "danse": { hint: "💃 Bouger en rythme", cat: 99 },
    "photo": { hint: "📷 Image capturée", cat: 99 },
    "dessin": { hint: "🎨 Image faite à la main", cat: 99 },
    "petit": { hint: "📏 Pas grand", cat: 99 },
    "grand": { hint: "📏 Très haut", cat: 99 },
    "mince": { hint: "📏 Pas épais", cat: 99 },
    "court": { hint: "📏 Petite distance", cat: 99 },
    "rapide": { hint: "⚡ Très vite", cat: 99 },
    "faible": { hint: "😔 Pas fort", cat: 99 },
    "chaud": { hint: "🔥 Haute température", cat: 99 },
    "froid": { hint: "🧊 Basse température", cat: 99 }
};
