// NIVEAU DIFFICILE (7+ lettres) - Mots longs et complexes

const DATA_HARD = {
    "baleine": "🐋 Très gros animal marin",
    "chameau": "🐪 Animal du désert avec des bosses",
    "famille": "👨‍👩‍👧‍👦 Groupe de personnes liées",
    "abeille": "🐝 Insecte qui fait du miel",
    "bonheur": "😊 Sentiment de grande joie",
    "février": "❄️ Deuxième mois de l'année",
    "décembre": "❄️ Douzième mois de l'année",
    "tempête": "⛈️ Mauvais temps avec vent et pluie",
    "rivière": "🌊 Cours d'eau",
    "lumiere": "💡 Ce qui éclaire et rend visible",
    "mercredi": "📅 Troisième jour de la semaine",
    "vendredi": "📅 Cinquième jour de la semaine",
    "dimanche": "📅 Jour de repos",
    "janvier": "❄️ Premier mois de l'année",
    "juillet": "☀️ Septième mois de l'année",
    "septembre": "🍂 Neuvième mois de l'année",
    "octobre": "🍂 Dixième mois de l'année",
    "novembre": "🍂 Onzième mois de l'année",
    "courage": "💪 Force face à la peur",
    "sourire": "😊 Expression du visage qui montre la joie",
    "heureux": "😄 Sentiment de grande joie et de bonheur",
    "mystere": "🔍 Enigme mystérieuse à résoudre",
    "magique": "🎩 Pouvoir surnaturel qui fait des miracles",
    "aventure": "🗺️ Voyage excitant plein de découvertes",
    "montagne": "⛰️ Grande élévation de terre",
    "quatorze": "14",
    "carotte": "🥕 Légume orange",
    "sorcier": "🧙 Homme sage qui connaît tous les sorts",
    "cristal": "💎 Pierre précieuse et brillante",
    "liberté": "🕊️ Droit de faire ce qu'on veut",
    "chocolat": "🍫 Friandise brune et sucrée",
    "chateau": "🏰 Grande maison fortifiée des rois",
    "courageux": "💪 Qualité de quelqu'un qui n'a pas peur",
    "magicien": "🧙 Personne qui pratique la magie",
    "princesse": "👸 Fille du roi et de la reine",
    "monstre": "👹 Créature effrayante et dangereuse",
    "tonnerre": "⚡ Bruit fort pendant l'orage",
    "arcenciel": "🌈 Arc-en-ciel avec toutes les couleurs",
    "papillon": "🦋 Insecte coloré qui vole",
    "elephant": "🐘 Très gros animal avec une trompe",
    "dauphin": "🐬 Animal marin intelligent et joueur",
    "pingouin": "🐧 Oiseau qui ne vole pas, nage bien",
    "spiderman": "🕷️ Super-héros qui grimpe aux murs",
    "superman": "🦸 Super-héros qui vole",
    "aladdin": "🧞 Jeune homme avec une lampe magique",
    "téléphone": "📱 Appareil pour appeler",
    "ordinateur": "💻 Machine pour travailler",
    "voiture": "🚗 Véhicule à 4 roues",
    "hôpital": "🏥 Lieu où on soigne",
    "fromage": "🧀 Produit laitier",
    "couronne": "👑 Bijou doré que portent les rois et reines",
    "chevalier": "⚔️ Guerrier courageux qui protège les gens",
    "dix-sept": "17",
    "dix-huit": "18",
    "dix-neuf": "19",
};

