// NIVEAU FACILE (3-4 lettres) - Mots courts et simples
// "[a-zàâäéèêëïîôùûüÿœæç]{4}":
const DATA_EASY = {
    "arc": "🏹 Arme qui lance des flèches très loin",
    "eau": "💧 Liquide transparent et vital",
    "mai": "🌸 Mois du printemps",
    "août": "☀️ Mois des vacances",
    "bob": "🏗️ Éponge qui vit dans un ananas",
    "buzz": "🚀 Astronaute de Toy Story",
    "chat": "🐱 Animal de compagnie ronronnant",
    "ours": "🐻 Gros animal poilu",
    "lion": "🦁 Roi de la jungle",
    "pain": "🥖 Aliment de base fait avec de la farine",
    "rage": "😡 Sentiment de colère",
    "peur": "😰 Sentiment d'angoisse",
    "joie": "😊 Sentiment de bonheur",
    "vert": "🌿 Couleur de l'herbe et des feuilles",
    "paix": "☮️ Absence de guerre et de conflit",
    "reve": "💭 Pensée qui vient quand on dort",
    "lune": "🌙 Astre qui brille la nuit dans le ciel",
    "epee": "⚔️ Arme brillante et pointue des chevaliers",
    "fee": "🧚 Petite créature magique avec des ailes",
    "un": "1",
    "deux": "2",
    "onze": "11",
    "vélo": "🚲 Véhicule à 2 roues",
    "cinq": "5",
    "six": "6",
    "sept": "7",
    "huit": "8",
    "neuf": "9",
    "dix": "10",
    "mur": "🧱 Paroi d'une maison",
    "lit": "🛏️ Meuble pour dormir",
    "sac": "🎒 Pour transporter des affaires",
    "roi": "👑 Chef d'un royaume",
    "feu": "🔥 Flammes chaudes",
    "air": "💨 Ce qu'on respire",
    "mer": "🌊 Grande étendue d'eau salée",
    "nez": "👃 Pour sentir les odeurs",
    "dos": "↩️ Arrière du corps",
    "ami": "🤝 Personne qu'on aime bien",
    "jeu": "🎮 Activité amusante",
    "bus": "🚌 Grand véhicule public",
    "ski": "⛷️ Sport d'hiver sur la neige",
    "lait": "🥛 Boisson blanche",
    "thé": "🍵 Boisson chaude",
    "sel": "🧂 Pour donner du goût",
    "noix": "🌰 Fruit à coque",
    "papa": "👨 Le père",
    "fils": "👦 Garçon de la famille",
    "rire": "😄 Faire ha ha ha",
    "parc": "🌳 Espace vert en ville",
    "auto": "🚗 Autre mot pour voiture",
    "voie": "🛣️ Chemin ou route",
    "pont": "🌉 Pour traverser l'eau",
    "tour": "🗼 Très haut bâtiment",
    "foot": "⚽ Sport avec un ballon",
    "golf": "⛳ Sport avec balle et trous",
    "boxe": "🥊 Sport de combat",
    "oeil": "👁️ Pour voir",
    "main": "✋ Avec cinq doigts",
    "pied": "🦶 Pour marcher",
    "bras": "💪 Entre épaule et main",
    "tête": "🧠 Contient le cerveau",
    "bol": "🥣 Pour manger la soupe",
    "clé": "🔑 Ouvre les portes",
    "lac": "🏞️ Eau douce entourée de terre",
    "île": "🏝️ Terre entourée d'eau",
    "miel": "🍯 Fait par les abeilles",
    "bébé": "👶 Très jeune enfant",
    "loup": "🐺 Hurle à la lune",
    "nuit": "🌙 Quand il fait noir",
    "jour": "☀️ Quand il fait jour",
    "porte": "🚪 Pour entrer",
    "taxi": "🚕 Voiture qu'on loue",
    "moto": "🏍️ Deux roues motorisé",
    "zéro": "0",
    "fin": "🏁 Terminé",
    "ange": "😇 Créature céleste",
    "élan": "🦌 Grand cerf du nord",
    "phare": "🗼 Tour qui guide les bateaux",
    "cage": "🔒 Prison pour animaux",
    "plume": "🪶 Ce qui couvre les oiseaux",
    "nid": "🪹 Maison des oiseaux"
};

